var Constants = {

  USERS_RECEIVED: "USERS_RECEIVED",
  PICS_RECEIVED: "PICS_RECEIVED",
  FOLLOWEES_RECEIVED: "FOLLOWEES_RECEVIED",
  PIC_RECEIVED: "PIC_RECEIVED",
  DELETE_PIC: "DELETE_PIC"

};

module.exports = Constants;
